### ISSUE TITLE
Issues to be fixed

### ISSUE THREAD

**Issue by qubit99** [HarmonyTheDatingApp/harmony-frontend#29]
1. Change URL names of signup to settings Change SignUpComponent name similary.
2. Add redirect to settings in 'SwipeDeck'
3. Add Log out functionality
4. Improve delete image button in Image Modal. Use overlay
5. Fix gender, interested gender default values of already logged in user in SignupForm.js
6. Add code to maintain login state throughout the app. A person not logged in shouldn't be able to navigate to views other than homepage.
7. Reduce size of login Button

**Comment by HarmonyTheDatingApp** [comment]
@2SkeePeR2 @stepupgithub

**Comment by HarmonyTheDatingApp** [comment]
UPDATE : Issues # 1, # 2, # 3 and # 6 has been fixed by @2SkeePeR2 . @stepupgithub could  work on others!
